### ISSUE TITLE
windows-compile-vs.bat cannot build binaries with OPCache JIT enabled

### ISSUE THREAD

**Issue by SkyLake-git** [pmmp/php-build-scripts#199]
According to compile.sh, ‘yes’ should be passed to --enable-opache-jit, but ‘on’ is used in windows-compile-vs.bat

**Comment by dktapps** [comment]
It works fine, it was done that way ever since PHP 8.0

**Comment by dktapps** [comment]
Never mind, I see it was introduced precisely to disable the JIT, which is why no one noticed this before: https://github.com/pmmp/PHP-Binaries/commit/00008706f939f86336af72d22e4dabd31e722d09

FWIW, you can't make inferences about the Windows build system from the *nix one. They are two completely separate systems. Windows uses some home-grown JS stuff and *nix uses autoconf. There's no guarantee of them being the same.
