### ISSUE TITLE
Android php DNS Error

### ISSUE THREAD

**Issue by DaisukeDaisuke** [pmmp/php-build-scripts#45]
I don't usually use English.
So my English is some strange point.

I have a one problem!
It's very important to use pmmp for Android.
I can't connect Internet because php file don't want to  resolve dns.
This php file compile by pmmp repository.
Who can teach me how to resolve it?
Please fix this issue.

I built php by bash on windows(ubuntu).
```
var_dump(file_get_contents('http://www.example.com/'));

Warning: file_get_contents(): php_network_getaddresses: gethostbyname failed. errno=2 in Command line code on line 1

Warning: file_get_contents(http://www.example.com/): failed to open stream: php_network_getaddresses: gethostbyname failed. errno=2 in Command line code on line 1
bool(false)
```

php version
```
PHP 7.2.2 (cli) (built: Feb 20 2018 19:26:51) ( ZTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```
app
https://play.google.com/store/apps/details?id=jackpal.androidterm

**Comment by KnownUnown** [comment]
This is a [known issue with PHP on Android](https://github.com/Falkirks/BuyCraft/issues/11). Maybe someone can `strace` php and see what's up?

**Comment by dktapps** [comment]
This is because `/etc/resolv.conf` does not exist on Android, it uses a different method for DNS resolution. There are a couple of ways to fix the issue - one is (if you have root access) create a `resolv.conf` somewhere and symlink it to `/etc/resolv.conf` - or the other way is to change the path of `/etc/resolv.conf` to something like `/sdcard/resolv.conf` where you can write to it, but that has to be done before building the musl libc.

[resolv.conf.txt](https://github.com/pmmp/php-build-scripts/files/1755874/resolv.conf.txt)

This is not something that can be conveniently done by our compile scripts either way.
